name: CI/CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Balance.sln

      - name: Build
        run: dotnet build Balance.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Balance.sln --configuration Release --no-build -o ./publish

      - name: Debug secrets
        run: |
          echo "DOCKER_USERNAME is: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/balance:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/balance:latest

